- roles/ethereum_node/defaults/main.yaml
- roles/ethereum_node/tasks/setup_cl.yaml
- roles/lighthouse/defaults/main.yaml
- roles/lighthouse/tasks/cleanup.yaml
- roles/lighthouse/tasks/main.yaml
- roles/lighthouse/tasks/setup.yaml
- roles/lodestar/defaults/main.yaml
- roles/lodestar/tasks/cleanup.yaml
- roles/lodestar/tasks/main.yaml
- roles/lodestar/tasks/setup.yaml
- roles/nimbus/defaults/main.yaml
- roles/nimbus/tasks/setup.yaml
- roles/prysm/defaults/main.yaml
- roles/prysm/tasks/cleanup.yaml
- roles/prysm/tasks/main.yaml
- roles/prysm/tasks/setup.yaml
- roles/teku/defaults/main.yaml
- roles/teku/tasks/setup.yaml
Added validator support to the following CL clients:
Additionally also:
Notes:
- Key imports will be done in a separate PR once I start using the roles on the 4844 testnets. With that I'll also add a bit better documentation on where keys should be put and in which format.
> Add validator feature to all CL clients

- roles/erigon/defaults/main.yaml
- roles/erigon/tasks/cleanup.yaml
- roles/erigon/tasks/setup.yaml
- roles/geth/defaults/main.yaml
- roles/geth/tasks/cleanup.yaml
- roles/geth/tasks/setup.yaml
Allow configuring custom networks by adding the required "init" step when using a custom genesis.json
> geth/erigon: support custom genesis configs.

- roles/arbitrum_node/tasks/main.yaml
- roles/beaconchain_explorer_aio/tasks/setup.yml
- roles/besu/tasks/setup.yaml
- roles/erigon/tasks/setup.yaml
- roles/ethereumjs/tasks/setup.yaml
- roles/geth/tasks/setup.yaml
- roles/lighthouse/tasks/setup.yaml
- roles/lodestar/tasks/setup.yaml
- roles/nethermind/tasks/setup.yaml
- roles/nimbus/tasks/setup.yaml
- roles/prysm/tasks/setup.yaml
- roles/teku/tasks/setup.yaml
Example problem when using it with geth:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: b'/data/geth/geth/chaindata/107911.ldb'
fatal: [bootnode-aws-ap-southeast-1-001]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line …
```
> never use recurse on data dirs as it could break ansible due to files appearing/disapearing

- roles/ethereum_node/defaults/main.yaml
- roles/ethereum_node/tasks/main.yaml
- roles/ethereum_node/tasks/setup_cl.yaml
- roles/ethereum_node/tasks/setup_snooper.yaml
- roles/json_rpc_snooper/defaults/main.yml
- The EL's keep running on the usual ports.
- The CL's will adapt and point to the right endpoint (EL directly, or snooper) depending on if the engine snooper is enabled.
- Also added the possibility to run the snooper on the default rpc port.
> ethereum_node: make rpc snooper available for default rpc or engine endpoints

- README.md
- roles/ethereum_node/defaults/main.yaml
- roles/ethereum_node/tasks/main.yaml
- roles/ethereum_node/tasks/setup_cl.yaml
- roles/ethereum_node/tasks/setup_snooper.yaml
- roles/json_rpc_snooper/README.md
- roles/json_rpc_snooper/defaults/main.yml
- roles/json_rpc_snooper/tasks/cleanup.yaml
- roles/json_rpc_snooper/tasks/main.yml
- roles/json_rpc_snooper/tasks/setup.yaml
One would use this role by setting the following variables:
- `ethereum_node_json_rpc_snooper_enabled`: `true`
- `ethereum_node_el_engine_endpoint`: `http://{{ json_rpc_snooper_container_name }}:{{ el_engine_snoop_port }}`
I think i need to define `el_engine_snoop_port` in `ethereum_node` but i need to check if that makes sense or not. its currently only defined in the role `json_rpc_snooper` as a default but i guess the config is happening at the `ethereum_node` level (since it needs to set `ethereum_node_el_engine_endpoint` when starting role `lighthouse`, etc). 
This would mean:
- Json rpc snooper gets added
- traffic passes through the defined snooper port
- snooper mitm logs the requests and passes it to the actual engine port
> Adding Json rpc snooper mitm

- roles/geth/defaults/main.yaml
- roles/geth/tasks/setup.yaml
- roles/nimbus/defaults/main.yaml
- roles/nimbus/tasks/setup.yaml
Nimbus requires a separate container to checkpoint sync. This PR adds the functionality to do so.
> Add nimbus checkpoint sync

- roles/arbitrum_node/tasks/main.yaml
- roles/besu/tasks/setup.yaml
- roles/erigon/tasks/setup.yaml
- roles/ethereumjs/tasks/setup.yaml
- roles/geth/tasks/setup.yaml
- roles/lighthouse/tasks/setup.yaml
- roles/lodestar/tasks/setup.yaml
- roles/nethermind/tasks/setup.yaml
- roles/nimbus/tasks/setup.yaml
- roles/prysm/tasks/setup.yaml
- roles/teku/tasks/setup.yaml
This existed before already, and was removed in here: https://github.com/ethpandaops/ansible-collection-general/commit/d905b59a997aa24223642ccf1fdf9c776505a3b0 
Unfortunately we can't rely on the `file` module using the [`recurse`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#parameter-recurse)  attribute. 
The problem with that approach is that there can be race conditions because the module does the following:
1. List all files that need to have the permissions fixed
2. Apply the permission fix
The problem happens if a file gets deleted between step 1 and 2 by a running node. Then ansible will crash saying that the file wasn't found and that it couldn't update its permissions. 
As a workaround, we need to use `chown` via the shell module.
> all clients: add data dir permission fixup 

- roles/bootstrap/tasks/add_github_ssh_key.yml
This fix will make sure to add each key on a new line. Currently there were accidentally being comma separated.
> bootstrap: fix for users that have multiple keys on github

- roles/ethereum_node/defaults/main.yaml
- roles/ethereum_node/tasks/main.yaml
- roles/mev_mock_relay_builder/README.md
- roles/mev_mock_relay_builder/defaults/main.yml
- roles/mev_mock_relay_builder/tasks/cleanup.yaml
- roles/mev_mock_relay_builder/tasks/main.yml
- roles/mev_mock_relay_builder/tasks/setup.yaml
Note: not to be confused with the flashbots relay and builder. 
Adds:
- Role for mock relay and builder
- Allows it to be enabled by the ethereum_node role
We need to make sure that the enable/disable isn't done in the group_vars definition of the `ethereum_node.yml` group, as then we would have one mock builder per node. Instead one per testnet would suffice. The playbook.yaml could probably ensure the hosts it runs on are only on the `mock_relay_and_builder` group perhaps, so even if mistakenly set as a group var it wouldn't run the role on all nodes. Lemme know if this is a fair way to set it up. The main reason its a part of the ethereum_node role is since it needs access to the EL and Beacon node RPC endpoints, Similar to Xatu/etc
> Adding role for Mario's mock builder and relay 

- roles/bootstrap/tasks/add_github_ssh_key.yml
Fixes https://github.com/ethpandaops/ansible-collection-general/issues/81
Now instead of using the lookup plugin (which executes directly on the ansible controller), we're downloading the keys directly from the servers. This won't make us get rate limited again since all the key queries will be done from the individual servers instead from the single ansible contoller machine.
> bootstrap: avoid lookup plugin due to github rate limiting

- roles/ethereum_genesis/tasks/generate_genesis.yaml
We want it to fail and stop. With `rescue` it would continue.
> ethereum_genesis: avoid calling rescue, we want it to fail and stop

- roles/ethereum_node/defaults/main.yaml
Falling back to the previous values if the other var isn't defined. 
I was getting this error on my CI runs:
>  FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'geth_container_name'
https://github.com/ethpandaops/ansible-collection-general/actions/runs/5588348838/jobs/10215015075
> ethereum_node: fix 'dict object' has no attribute 'geth_container_name'

- roles/nethermind/defaults/main.yaml
Reverts ethpandaops/ansible-collection-general#127
Waiting until a new nethermind release as this doesn't match current `latest`  ( 1.20.1 )
> Revert "Fixing nethermind entrypoint "

- roles/beaconlight_explorer/README.md
- roles/beaconlight_explorer/defaults/main.yml
- roles/beaconlight_explorer/tasks/cleanup.yml
- roles/beaconlight_explorer/tasks/main.yml
- roles/beaconlight_explorer/tasks/setup.yml
Added new role `ethpandaops.general.beaconlight_explorer`, which installs my [lightweight beaconchain explorer](https://github.com/pk910/light-beaconchain-explorer) using docker images (defaults to the latest stable release).
Structure is mostly copied from the `blockscout` role, so it should hopefully be conform with the repository standards ;)
Works on my side in a [test-playbook](https://gist.github.com/pk910/04188cfe175d990cc6ba5247f4f690cb) which deploys the explorer for ephemery on a test vm.
> Added `beaconlight_explorer` role that installs light-beaconchain-explorer

- roles/generate_kubernetes_config/defaults/main.yaml
- roles/generate_kubernetes_config/templates/powfaucet.yaml.j2
- roles/powfaucet/defaults/main.yml
powfaucet needs to know how many proxy servers are in front of it.
Otherwise it cannot safely select the correct remote IP from the list of forwarder addresses in the `X-Forwarded-For` header.
> added config variables for powfaucet proxy count

- roles/generate_kubernetes_config/templates/dora.yaml.j2
Made the pull policy logic more flexible.
It'll now use `Always` for all tags that contain the word "latest".
This should work fine with the new build workflow, which uses version specific tags (`master-<commit>`) & latest tags (`master-latest`).
Testnet related branches follow the same schema, eg.  `verkle-support-<commit>` & `verkle-support-latest`
> Set dora pull policy to `Always` if tag name contains `latest`

- roles/bootstrap/defaults/main.yml
The OVH debian template didn't have cron installed.
> bootstrap: add cron to default packages to install

- roles/ethereum_genesis/README.md
The md link symbol is broken, use this change to fix it.
> docs: fix the link error in the markdown.

- .github/workflows/integration.yaml
- requirements.yaml
- roles/bootstrap/defaults/main.yml
- roles/bootstrap/handlers/main.yml
- roles/bootstrap/meta/main.yml
- roles/bootstrap/meta/requirements.yml
- roles/bootstrap/molecule/default/converge.yml
- roles/bootstrap/molecule/default/molecule.yml
- roles/bootstrap/molecule/default/verify.yml
- roles/bootstrap/tasks/main.yml
- roles/bootstrap/tasks/prepare/gather_facts.yml
- roles/bootstrap/tasks/prepare/main.yml
- roles/bootstrap/vars/main.yml
- roles/ethereum_node/molecule/default/molecule.yml
Move steps that were used by the `robertdebock.bootstrap` role to the bootstrap role itself.
So this mainly includes, making sure that the system is ready to be managed by ansible, by installing the minimal required packages (e.g. python, sudo ... )
> bootstap: move dependency code to role itself

- .github/workflows/integration.ethereum_node.yaml
- .tool-versions
- requirements.txt
- roles/beacon_stopper/defaults/main.yaml
- roles/beaconchain_explorer_aio/defaults/main.yml
- roles/erigon/defaults/main.yaml
- roles/ethereum_inventory_web/defaults/main.yaml
- roles/ethereum_testnet_config/defaults/main.yaml
- roles/generate_basic_auth_nginx/defaults/main.yaml
- roles/generate_kubernetes_config/defaults/main.yaml
- roles/grandine/defaults/main.yaml
- roles/hetzner_vswitch/defaults/main.yaml
- roles/lighthouse/defaults/main.yaml
- roles/lodestar/defaults/main.yaml
- roles/nimbus/defaults/main.yaml
- roles/prysm/defaults/main.yaml
- roles/reth/defaults/main.yaml
- roles/teku/defaults/main.yaml
Version Upgrades:
- Shellcheck `0.9.0` -> `0.10.0` https://github.com/koalaman/shellcheck/releases
- Python `3.11.4` -> `3.12.4`
- Ansible `7.5.0` -> `10.1.0` ( Which is actually `2.14.x` to `2.17.1` as per https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) 
- Ansible Lint `6.15.0 to `24.6.0` ( They changed their release numbers and jumped from v6 to v24 https://github.com/ansible/ansible-lint/releases )
- Molecule `5.0.1` to `24.6.0` ( Same as ansible lint, they jumped from v6 to v24 https://github.com/ansible/molecule/releases ) 
- pip `23.1.2` to `23.3.2`
- netaddr `0.8.0` to `1.3.0` ( needed by some ansible modules).
> Bump ansible and other dependencies

- roles/cl_bootnode/defaults/main.yaml
`9001` is now taken by `quic`, so moving this range to a different one. Otherwise if cl-bootnode and quic is on the same node, we face an contentious deployment.
> making more configurible

- roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2
We didn't change any of the paths for metadata inside the containers. So this metadata change broke all the kube nodes stuff.
> fix: metadata not needed everywhere

- .github/workflows/integration.ethereum_node.yaml
- .github/workflows/integration.yaml
- README.md
- requirements.yaml
- roles/ethereum_node/defaults/main.yaml
- roles/ethereum_node/molecule/default/molecule.yml
- roles/ethereum_node/tasks/addons/external_block_builder.yaml
- roles/ethereum_node/tasks/main.yaml
- roles/ethereum_node/tasks/setup_cl.yaml
- roles/ethereum_node/vars/main.yaml
- roles/mev_boost/defaults/main.yml
- roles/mev_boost/molecule/default/converge.yml
- roles/mev_boost/molecule/default/molecule.yml
- roles/mev_boost/molecule/default/verify.yml
- roles/mev_rs/README.md
- roles/mev_rs/defaults/main.yml
- roles/mev_rs/molecule/default/converge.yml
- roles/mev_rs/molecule/default/molecule.yml
- roles/mev_rs/molecule/default/verify.yml
- roles/mev_rs/tasks/cleanup.yaml
- roles/mev_rs/tasks/main.yml
- roles/mev_rs/tasks/setup.yaml
- roles/nethermind/defaults/main.yaml
Solves: https://github.com/ethpandaops/ansible-collection-general/issues/221 
Changes in this PR:
- Added `mev_rs` role with a simple molecule test (Run container, verify it started, print logs).
- Added the same molecule test to `mev_boost`.
- Changed the `ethereum_node` role so that you can choose between `mev_boost` and `mev_rs` as the external block builder. It's also possible to provide `custom`. When using a custom builder, you need to provide your own endpoint.
> Add mev-rs role

- .github/workflows/integration.ethereum_node.yaml
- README.md
- roles/lighthouse/defaults/main.yaml
- roles/lighthouse/meta/main.yaml
- roles/lighthouse/tasks/cleanup.yaml
- roles/lighthouse/tasks/setup.yaml
- roles/lodestar/defaults/main.yaml
- roles/lodestar/meta/main.yaml
- roles/lodestar/tasks/cleanup.yaml
- roles/lodestar/tasks/setup.yaml
- roles/nimbus/defaults/main.yaml
- roles/nimbus/tasks/cleanup.yaml
- roles/nimbus/tasks/main.yaml
- roles/nimbus/tasks/setup.yaml
- roles/prysm/defaults/main.yaml
- roles/prysm/meta/main.yaml
- roles/prysm/tasks/cleanup.yaml
- roles/prysm/tasks/setup.yaml
- roles/teku/defaults/main.yaml
- roles/teku/tasks/cleanup.yaml
- roles/teku/tasks/main.yaml
- roles/teku/tasks/setup.yaml
This feature is useful when we just want to run the validator client. 
e.g. On the lighthouse role, we can now achieve this by doing:
```yaml
lighthouse_enabled: false
lighthouse_validator_enabled: true
```
Additionally, I've updated the github workflow to run the `ethereum_node` molecule tests whenever it detects a change on a CL/EL role. It will only run tests against a role that has changed. E.g. If you change the lighthouse role, it will run the test with lighthouse + all the EL pairs.
> Possiblity to run isolated validator client on consensus nodes + CI change detection improvements

- roles/generate_kubernetes_config/templates/dora.yaml.j2
Feature from https://github.com/ethpandaops/dora/pull/117
> generate_kubernetes_config: enable additional sensitive peer infos on dora

- roles/prysm/defaults/main.yaml
- roles/prysm/tasks/setup.yaml
It will enable pretty logging for Prysm BN/VC.
Before:
After:
> Prysm BN/VC: Add `tty: true`

- roles/generate_kubernetes_config/files/ingress.config.yaml.tpl
Fix for `ingress-nginx-public-controller-678c58d9d6-8p8vj controller 2024-10-21T10:41:45.462803094+02:00 2024/10/21 08:41:45 [crit] 165#165: *18127 SSL_do_handshake() failed (SSL: error:0A000458:SSL routines::tlsv1 unrecognized name:SSL alert number 112) while SSL handshaking to upstream, client: 185.71.112.107, server: config.pectra-devnet-4.ethpandaops.io, request: "GET /api/v1/nodes/validator-ranges HTTP/1.1", upstream: "https://209.38.212.82:443/meta/api/v1/validator-ranges.json", host: "config.pectra-devnet-4.ethpandaops.io"`
`proxy_ssl_name=`
> Allows overriding the server name used to [verify](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_verify) the certificate of the proxied HTTPS server and to be [passed through …
> fix SSL error on config upstreams

- roles/prysm/defaults/main.yaml
As of [5.1.1](https://github.com/prysmaticlabs/prysm/releases/tag/v5.1.1).
> fix: prysm removed grpc flag

- roles/ethereum_testnet_config/defaults/main.yaml
- roles/ethereum_testnet_config/tasks/main.yaml
this is needed as the repo cloned doesn't always contain the files needed by the node at its root. this change allows us to clone the repo to a temp location and then move the required files to the needed destination.
> adding config options to eth_testnet_config

- roles/ethereum_node_fact_discovery/tasks/execution_layer.yaml
The bootnode binary has been removed
> fix(ethereum_node_fact_discovery): use devp2p to get enode instead of bootnode binary

- roles/docker_cleanup/defaults/main.yaml
- roles/docker_cleanup/tasks/main.yaml
The problem is that `docker system prune` will cleanup:
- all stopped containers
- all networks not used by at least one container
- all dangling images
- unused build cache
I don't think that we want it to cleanup stopped docker containers by default. This affected me on certain machines. 
Having the default policy just to prune images, should be enough.
> docker_cleanup: limit default pruning to images only and make it configurable

- roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2
Due to Service "teku-geth-001-p2p-0" is invalid: spec.ports[0].nodePort: Invalid value: 32918: provided port is not in the valid range. The range of valid ports is 30000-32767 (retried 5 times)
> generate_kubernetes_config: fix upper port limit

- roles/mev_relay/defaults/main.yml
`env` is a dict. not a list: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-env
> mev_relay: update default env vars - expect dict, not list.

- .github/actions/setup/action.yaml
The newest asdf version 0.16.0 is rewritten in go and requires some new setup. I'll stick to 0.15.0 until we decide to update this across our stack.
> downgrade asdf

- .github/actions/setup/action.yaml
- .github/workflows/lint.yaml
- .gitignore
- Makefile
- README.md
- requirements.txt
The problem with the most recent linting runs was that:
1. `ansible-lint` created a `.ansible` directory locally where it cached some stuff (roles/collections...)
2. `ansible-test sanity` also checked that `.ansible` directory.
This PR adds `.ansible` to gitignore and also excludes it from the sanity test command.
Additionaly, I've moved some commands to a Makefile to make it easier to run the whole lint job by just running `make lint`.
> fix: ansible-lint CI failing

- roles/beaconchain_explorer_aio/tasks/cleanup.yml
- roles/beaconchain_explorer_aio/tasks/setup.yml
- roles/xatu_stack/handlers/main.yaml
- roles/xatu_stack/tasks/cleanup.yaml
docker-compose v1 is deprecated and using it will print: `[DEPRECATION WARNING]: community.docker.docker_compose has been deprecated. This module uses docker-compose v1, which is End of Life since July 2022. Please migrate to community.docker.docker_compose_v2. This 
feature will be removed from community.docker in version 4.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`. 
This PR updates the ansible module to use docker_compose_v2 instead of the v1.
> Update docker_compose module to docker_compose_v2 

- roles/xatu_sentry/defaults/main.yaml
This PR adds `xatu_sentry_config_server_tls_enabled` to control whether the xatu server is configured with tls when using the xatu_sentry role. 
Please let me know if configuration additions like this are okay! 😄
> Add xatu_sentry_config_server_tls_enabled to xatu-sentry configuration

- .github/workflows/integration.ethereum_node.scheduled.yaml
- .github/workflows/integration.ethereum_node.yaml
- .github/workflows/integration.yaml
- .github/workflows/lint.yaml
This PR updates GitHub Actions to use pinned commit hashes for better security.
> Update GitHub Actions to use pinned hashes

- roles/bootstrap/defaults/main.yml
Due to :
```
Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'ethpandaops.general.url_cached'. Error was a <class 'TimeoutError'>, original message: The read operation timed out. The read operation timed out
```
> bootstrap: increase timeout from 10s to 20s when fetching keys

- roles/arbitrum_node/tasks/main.yaml
- roles/besu/tasks/setup.yaml
- roles/blobber/tasks/setup.yaml
- roles/charon/tasks/setup.yaml
- roles/erigon/tasks/setup.yaml
- roles/ethereumjs/tasks/setup.yaml
- roles/geth/tasks/setup.yaml
- roles/grandine/tasks/setup.yaml
- roles/lighthouse/tasks/setup.yaml
- roles/lodestar/tasks/setup.yaml
- roles/mev_flood/tasks/setup.yaml
- roles/nethermind/tasks/setup.yaml
- roles/nimbus/tasks/setup.yaml
- roles/nimbusel/tasks/setup.yaml
- roles/prysm/tasks/setup.yaml
- roles/reth/tasks/setup.yaml
- roles/teku/tasks/setup.yaml
fixes https://github.com/ethpandaops/ansible-collection-general/issues/379 
Sometimes files get deleted by the running apps and chown will throw some errors. We can safely ignore those.
> ethereum_node: ignore errors giving by chown

- roles/generate_kubernetes_config/templates/dora.yaml.j2
There PR removes an extra colon at the `API_ENABLED` env var of dora helm chart which causes issue when using the chart.
> Remove extra colon in dora helm chart values

- roles/docker_watchtower/defaults/main.yaml
This should also fix the problem of watchtower not respecting the container specific timeouts when doing "docker stop".
> watchtower: update to a more maintaned fork
