ethpandaops/ansible-collection-general

- README.md
- roles/ethereum_auth_jwt/README.md
- roles/ethereum_auth_jwt/defaults/main.yaml
- roles/ethereum_auth_jwt/tasks/main.yaml
- roles/geth/README.md
- roles/geth/defaults/main.yaml
- roles/geth/meta/main.yaml
- roles/geth/tasks/main.yaml
- roles/nimbus/README.md
- roles/nimbus/defaults/main.yaml
- roles/nimbus/meta/main.yaml
- roles/nimbus/tasks/main.yaml
- roles/teku/README.md
- roles/teku/defaults/main.yaml
- roles/teku/meta/main.yaml
- roles/teku/tasks/main.yaml
> Add teku, nimbus and geth client roles 

- .gitignore
- README.md
- ansible.cfg
- galaxy.yml
- requirements.yaml
- roles/docker_cleanup/README.md
- roles/docker_cleanup/defaults/main.yaml
- roles/docker_cleanup/tasks/main.yaml
- roles/docker_network/README.md
- roles/docker_network/defaults/main.yaml
- roles/docker_network/tasks/main.yaml
- roles/geth/README.md
- roles/nimbus/README.md
- roles/node_exporter/README.md
- roles/node_exporter/defaults/main.yaml
- roles/node_exporter/tasks/main.yaml
- roles/prometheus/README.md
- roles/prometheus/defaults/main.yaml
- roles/prometheus/handlers/main.yaml
- roles/prometheus/tasks/main.yaml
- roles/teku/README.md
- setup.sh
New roles:
- docker_cleanup
- docker_network
- node_exporter
- prometheus
> Add more common roles

- README.md
- galaxy.yml
- playbooks/bootstrap_server.yaml
- requirements.yaml
- roles/bootstrap/README.md
- roles/bootstrap/defaults/main.yml
- roles/bootstrap/handlers/main.yml
- roles/bootstrap/meta/main.yml
- roles/bootstrap/meta/requirements.yml
- roles/bootstrap/tasks/main.yml
- roles/k3s/tasks/prereq.yaml
- roles/oh_my_zsh/README.md
- roles/oh_my_zsh/defaults/main.yaml
- roles/oh_my_zsh/meta/main.yml
- roles/oh_my_zsh/meta/requirements.yml
- roles/oh_my_zsh/tasks/main.yaml
Add commonly used bootstrap roles and playbook
> Bootstrap roles + playbook

- README.md
- roles/json_exporter/README.md
- roles/json_exporter/defaults/main.yaml
- roles/json_exporter/handlers/main.yaml
- roles/json_exporter/tasks/main.yaml
I've started using this to query some HTTP APIs and transform their JSON responses into metrics.
> feat(roles): add json_exporter

- roles/lodestar/defaults/main.yaml
Reverts ethpandaops/ansible-collection-general#66
> Revert "lodestar: disable enr.udp temporarily due to bug"

- roles/bootstrap/defaults/main.yml
- roles/bootstrap/tasks/add_github_ssh_key.yml
- roles/bootstrap/tasks/main.yml
- Removed _additional_ ssh key vars.
- Add comment to SSH key so that we know from which user it came from
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#defining-inner-and-outer-variable-names-with-loop-var
> bootstrap: add comment to github key origins

- README.md
- roles/hetzner_vswitch/README.md
- roles/hetzner_vswitch/defaults/main.yaml
- roles/hetzner_vswitch/handlers/main.yaml
- roles/hetzner_vswitch/tasks/cleanup.yaml
- roles/hetzner_vswitch/tasks/main.yaml
- roles/hetzner_vswitch/templates/interface.j2
Hetzner vswitch for connecting dedicated to cloud nodes https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch/
> feat(hetzner-vswitch): init

- .github/workflows/integration.ethereum_node.yaml
- .github/workflows/integration.yaml
- README.md
Fixes:
As per https://github.com/dorny/paths-filter#change-detection-workflows
> ci: fix up change detection on master branch

- roles/nethermind/defaults/main.yaml
- roles/nethermind/tasks/setup.yaml
Breaking change: 
https://github.com/NethermindEth/nethermind/commit/19b7eb4900373b2038d0508ed0d625ba8ad03d75
> Fixing nethermind entrypoint 

- roles/generate_kubernetes_config/templates/dora.yaml.j2
- roles/generate_kubernetes_config/templates/testnet-homepage.yaml.j2
fixed 2 more lightweigt beaconchain explorer references
> fix missed dora renamings

- README.md
- roles/goomy/README.md
- roles/goomy/defaults/main.yaml
- roles/goomy/handlers/main.yaml
- roles/goomy/tasks/cleanup.yaml
- roles/goomy/tasks/main.yaml
- roles/goomy/tasks/setup.yaml
Added `goomy` role, which spins up an instance of the [goomy](https://github.com/ethpandaops/goomy-blob) blob testing tool.
> Added role for goomy the blob tool

- README.md
- roles/powfaucet/README.md
- roles/powfaucet/defaults/main.yml
- roles/powfaucet/tasks/cleanup.yml
- roles/powfaucet/tasks/main.yml
- roles/powfaucet/tasks/setup.yml
added a role for the [PoWFaucet](https://github.com/pk910/PoWFaucet)
> Added `powfaucet` role

- roles/lodestar/defaults/main.yaml
G11tech can't make up his mind, so now they need builder flag in the validator 😂
> fix: lodestar-validator builder flag enabled

- roles/ethereum_genesis/tasks/generate_genesis.yaml
fixes https://github.com/ethpandaops/ansible-collection-general/issues/203
> ethereum_genesis: fix to handle the different failure conditions based on OS

- roles/node_exporter/defaults/main.yaml
- roles/node_exporter/tasks/main.yaml
for easy addable args like in eth el and cl roles
> Add node exporter extra args value

- roles/generate_kubernetes_config/defaults/main.yaml
- roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2
add random nodeport based on seed.
> fix: add nodeport

- roles/erigon/defaults/main.yaml
> erigon: fix docker image

- .github/actions/setup/action.yaml
- .github/workflows/integration.ethereum_node.scheduled.yaml
- .github/workflows/integration.ethereum_node.yaml
- .github/workflows/integration.yaml
- .github/workflows/lint.yaml
This PR updates GitHub Actions to use pinned commit hashes for better security.
> Update GitHub Actions to show versions as a comment

- roles/generate_kubernetes_config/defaults/main.yaml
- roles/generate_kubernetes_config/templates/xatu-mimicry.yaml.j2
Add helm chart configuration and template for deploying Xatu Mimicry service in Kubernetes environments with proper resource management and output configuration.
> feat: add xatu-mimicry kubernetes integration

- roles/generate_kubernetes_config/templates/dora.yaml.j2
Blocked on: https://github.com/ethpandaops/dora/pull/421
> feat: enable API on dora by default

- roles/ethereum_node/tasks/addons/blobber.yaml
- roles/ethereum_node/tasks/addons/docker_watchtower.yaml
- roles/ethereum_node/tasks/addons/external_block_builder.yaml
- roles/ethereum_node/tasks/addons/grafana_alloy.yaml
- roles/ethereum_node/tasks/addons/metrics_exporter.yaml
- roles/ethereum_node/tasks/addons/snooper.yaml
- roles/ethereum_node/tasks/addons/xatu_sentry.yaml
- roles/mev_relay/defaults/main.yml
Should enable us to trigger subroles with specific tag without rolling the whole ethereum node role.
> feat: add tags for optional roles

- roles/lighthouse/defaults/main.yaml
depends on https://github.com/sigp/lighthouse/pull/8083
> fix: update lh supernode flag
